# Generated by Django 2.0.1 on 2018-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pew', models.CharField(max_length=32)),
                ('eml', models.CharField(max_length=32)),
            ],
        ),
    ]
