# Generated by Django 2.0.1 on 2018-01-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pew',
            new_name='pwd',
        ),
    ]
